#!/usr/bin/env bash

# defaults write com.apple.dock workspaces-auto-swoosh -bool FALSE # https://superuser.com/a/1802693
# https://medium.com/swlh/top-mac-os-default-behaviors-you-should-consider-changing-419b679fe290
defaults write com.apple.dock static-only -bool true && \
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true && \
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true && \
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true && \
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true && \
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

alias showfiles='defaults write com.apple.finder AppleShowAllFiles true && killall Finder'
alias hidefiles='defaults write com.apple.finder AppleShowAllFiles false && killall Finder'